### ISSUE TITLE
Load Railway menu option closes the currently open railway prematurely if user cancels load

### ISSUE THREAD

**Issue by stephensmith9** [AlbertBall/railway-dot-exe#11]
Selecting the File | Load Railway... menu option immediately closes the currently displayed railway (if one is open) and if the user decides to abort the load of a new railway they are dumped back into RailOS with no railway loaded. In my opinion, the currently loaded railway should not be closed until the user selects a new railway file and confirms.

Discovered this when I simply wanted to see what other railways were available without leaving the currently loaded one I had open.

Low priority but I would consider this _unexpected_ UX.

Running Windows 10 Home Version 22H2 OS Build 19045.4170 and RailOS 2.19.1 - 64 bit

**Comment by stephensmith9** [comment]
Code modified to fix this, but awaiting consensus from the team (Albert and Kristian) to see if this is a desired enhancement. If approved I will commit to my fork and make a pull request.

**Comment by AlbertBall** [comment]
This is such an obvious improvement that it's strange it had never occurred to me - or anyone else before you as no-one has mentioned it until now.  I'll bet there are plenty of other things like this waiting to be fixed.  Yes please submit your pull request and I'll pull it into Post_v2.19.1_Dev.  I keep updates in that branch until ready to release a new version and then merge it with master.

**Comment by zarethrex** [comment]
> Code modified to fix this, but awaiting consensus from the team (Albert and Kristian) to see if this is a desired enhancement. If approved I will commit to my fork and make a pull request.

Contributions are always welcome, the project is open source so please do open MRs with any improvements you have made 🙂
